#! /bin/sh
### BEGIN INIT INFO
# Provides:          jarvis
# Required-Start:    $network $remote_fs $syslog networking
# X-Start-After:     $network
# Required-Stop:     $network $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: initscript for Jarvis
### END INIT INFO

# Author: Yannick Roffin
# Thanks to script author: Leonid Shevtsov <leonid@shevtsov.me>
# Cf. https://leonid.shevtsov.me/post/how-to-make-a-java-daemon-with-start-stop-daemon

# Do NOT "set -e"

PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="jarvis"
NAME="jarvis-service"
CWD=/home/jarvis
USER=root
GROUP=jarvis
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME

# ex: http://192.168.1.111:8082
jarvis_server_url=http://127.0.0.1:8080
# ex: remote-module-name
jarvis_module_name=default
# ex: 192.168.1.47
jarvis_module_interface=0.0.0.0
jarvis_module_port=7000
jarvis_option_wiringpi=false
jarvis_option_mfrc522=false
jarvis_option_advertise=true
# dio
jarvis_option_dio=false
# teleinfo
jarvis_option_teleinfo_active=false
jarvis_option_teleinfo=false
# razberry
jarvis_option_razberry_active=false
# ex: ZWayVDev_zway_7-0-49-1
jarvis_option_razberry_devices=""
jarvis_option_razberry=false
# ex: Basic 0123456789=
jarvis_option_razberry_auth=""
# ex: http://192.168.1.111:8083/ZWaveAPI/Run
jarvis_option_razberry.url=""
# ex: 192.168.1.47
jarvis_option_mongodb=${jarvis_module_interface}

EXECUTABLE_COMMAND=/home/jarvis/jarvis-rest-module-0.0.1-SNAPSHOT.arm
EXECUTABLE_ARGS="`echo start \
 --jarvis.module.name ${jarvis_module_name} \
 --jarvis.module.interface ${jarvis_module_interface} \
 --jarvis.module.port ${jarvis_module_port} \
 --jarvis.server.url ${jarvis_server_url} \
 --jarvis.option.advertise ${jarvis_option_advertise} \
 --jarvis.option.wiringpi ${jarvis_option_wiringpi} \
 --jarvis.option.dio ${jarvis_option_dio} \
 --jarvis.option.teleinfo ${jarvis_option_teleinfo} \
 --jarvis.option.teleinfo.active ${jarvis_option_teleinfo_active} \
 --jarvis.option.razberry ${jarvis_option_razberry} \
 --jarvis.option.razberry.active ${jarvis_option_razberry_active} \
 --jarvis.option.razberry.devices ${jarvis_option_razberry_devices} \
 --jarvis.option.razberry.auth ${jarvis_option_razberry_auth} \
 --jarvis.option.razberry.url ${jarvis_option_razberry_url} \
 --jarvis.option.mfrc522 ${jarvis_option_mfrc522} \
 --jarvis.option.mongodb ${jarvis_option_mongodb}`"

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
# and status_of_proc is working.
. /lib/lsb/init-functions

#
# Function that starts the daemon/service
#
do_start()
{
  # Return
  #   0 if daemon has been started
  #   1 if daemon was already running
  #   2 if daemon could not be started
  start-stop-daemon --start \
    --quiet \
    --pidfile $PIDFILE \
    --user $USER \
    --exec $EXECUTABLE_COMMAND \
    --test > /dev/null \
    || return 1
  # FIXME: export environment variables here
  start-stop-daemon --start \
    --quiet \
    --make-pidfile \
    --pidfile $PIDFILE \
    --chuid $USER \
    --user $USER \
    --group $GROUP \
    --chdir $CWD \
    --background \
    --exec $EXECUTABLE_COMMAND \
    -- $EXECUTABLE_ARGS \
    || return 2
}

#
# Function that stops the daemon/service
#
do_stop()
{
  # Return
  #   0 if daemon has been stopped
  #   1 if daemon was already stopped
  #   2 if daemon could not be stopped
  #   other if a failure occurred
  start-stop-daemon --stop \
    --quiet \
    --user $USER \
    --pidfile $PIDFILE \
    --exec $EXECUTABLE_COMMAND \
    --retry=TERM/30/KILL/5
  RETVAL="$?"
  [ "$RETVAL" = 2 ] && return 2
  rm -f $PIDFILE
  return "$RETVAL"
}

#
# Function that checks if the daemon is running
#
do_status()
{
  start-stop-daemon \
    --start \
    --test \
    --oknodo \
    --pidfile $PIDFILE \
    --user $USER \
    --exec $EXECUTABLE_COMMAND
}

VERBOSE=yes

case "$1" in
  start)
  [ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
  do_start
  case "$?" in
    0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
    2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
  esac
  ;;
  
  stop)
  [ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
  do_stop
  case "$?" in
    0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
    2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
  esac
  ;;

  status)
  do_status
  ;;

  restart|force-reload)

  log_daemon_msg "Restarting $DESC" "$NAME"
  do_stop
  case "$?" in
    0|1)
    do_start
    case "$?" in
      0) log_end_msg 0 ;;
      1) log_end_msg 1 ;; # Old process is still running
      *) log_end_msg 1 ;; # Failed to start
    esac
    ;;
    *)
    # Failed to stop
    log_end_msg 1
    ;;
  esac
  ;;
  *)
  echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
  exit 3
  ;;
esac
